# Generated by Django 4.0.4 on 2022-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Process'), (2, 'Complated'), (3, 'Cancelled')], default=0),
        ),
    ]
